import type { NextPage } from "next";
import Head from "next/head";
import { Open_Sans } from "next/font/google";

const font = Open_Sans({ subsets: ["latin"] });

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${font.className}`}>
        <h1>Beer collection</h1>
      </main>
    </>
  );
};

export default Home;
